#!/usr/bin/python3
import psycopg2
conn = psycopg2.connect(database = "________", user = "________", password = "________", host = "127.0.0.1", port = "5432")
print ("Opened database successfully")

cur = conn.cursor()
cur.execute('DROP TABLE IF EXISTS CLIENTS')
conn.commit()
cur.execute('CREATE TABLE  CLIENTS (ID TEXT PRIMARY KEY NOT NULL, NAME TEXT NOT NULL, POSITION INT NOT NULL, REG_DATE TIMESTAMP NOT NULL);')
print ("Table clients created successfully")

cur.execute('DROP TABLE IF EXISTS QUESTIONS')
conn.commit()
cur.execute('CREATE TABLE  QUESTIONS (ID UUID PRIMARY KEY NOT NULL, QUESTION TEXT NOT NULL, ANSWER TEXT NOT NULL);')
print ("Table questions created successfully")

cur.execute('DROP TABLE IF EXISTS TALKS')
conn.commit()
cur.execute('CREATE TABLE  TALKS (ID SERIAL PRIMARY KEY NOT NULL, MESSAGE TEXT NOT NULL, TYPE TEXT NOT NULL);')
print ("Table talks created successfully")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Давай начнем с того, что обсудим, что такое управление. Я буду рассказывать просто, без тяжеловесных терминов.', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Управление - это деятельность над деятельностью. То есть управляя, руководитель не сам выполняет какие-либо рабочие операции, а организует работу других людей, действует их руками.', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Конечно, иногда руководитель тоже работает как специалист, но он должен делать это в том случае, когда сотрудники не справляются, тогдла руководитель это компенсирует. Самое важное помнить: чем больше ты работаешь как специалист, тем меньше управляешь!', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('pic1.png', 'IMAGE');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Цель руководителя - организовать процесс выполнения задач и достижения целей. Но бывает такое, что сотрудник не выполняет задачи, которые поставил перед ним руководитель. Как ты думаешь, почему так происходит?', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Верно, но не только, на самом деле сотрудник мог и не хотеть, и не понять что делать. Всего можно выделить 4 причины', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Ты прав! Но это еще не все. Сотрудник мог не понять, что делать, не иметь ресурсов и так далее. Всего можно выделить 4 причины.', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('В точку! Но есть еще пара причин. Сейчас все расскажу.', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Итак, есть 4 причины, по которым сотрудник может не выполнить поставленную перед ним задачу: не мог, не понял, не умел, не хотел. Если твой подчиненный не выполнил задачу или не в срок, проверять причины необходимо именно в этом порядке.', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('И знаешь, что самое интересное? Если сотрудник не выполнил задачу, то в этом есть доля и твоей управленческой недоработки. Согласен?', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('При чём тут я?', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Понятное дело', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('А при том, что значит какая-то из управленческих функций не была реализована тобой', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Солидарен с тобой, смотри на картинку, и станет понятно, в чём управленческая ошибка, в зависимости от причины невыполнения задачи', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Теперь ты знаешь, что нужно делать, чтобы избежать таких досадных управленческих недоразумений и в разы увеличить процент выполненных задач. Для этого нужно знать и выполнять ключевые управленческие функции', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Ну что ж, теперь ты знаешь, какие есть функции у руководителя и какой функции нужно уделить больше внимания, если сотрудник не выполняет задачу.', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Хочу спросить у тебя, как ты думаешь, какую функцию необходимо прокачать именно тебе?', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Спасибо, что поделился. В этом курсе мы коротко рассмотрим некоторые из этих функций в рамках изучаемых тем.', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Мы с тобой узнали, что такое управление, а также о причинах невыполнения задач. Давай я задам тебе пару вопросов, чтобы ты мог проверить, насколько хорошо усвоил материал.', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Вопрос 1. Тимлид Денис сегодня целый час разговаривал со своей сотрудницей Анной, которая в последнее время пала духом и ничего не хочет, совершает ошибки. Денис пытался подбодрить её и найти для неё интересные задачи. Денис в данном случае выполнял функцию специалиста или руководителя?', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Не согласен с тобой! В данном случае он проводил мотивационную беседу, а значит, работал как руководитель.', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('В точку! Мотивирование - функция руководителя.', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Вопрос 2. Если для выполнения задачи руководитель выбрал сотрудника, у которого на данный момент нет ресурса для выполнения задачи, то какую функцию он не реализовал?', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Верно! Выбирая кому поручить задачу, нужно всегда анализировать, у кого есть время, силы и другие ресурсы для её выполнения, то есть планировать', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Не соглашусь! Выбирая, кому поручить задачу, нужно всегда анализировать, у кого есть время, силы и другие ресурсы для её выполнения, то есть планировать', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Увы, нет. Выбирая, кому поручить задачу, нужно всегда анализировать, у кого есть время, силы и другие ресурсы для её выполнения, то есть планировать.', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Вопрос 3. Сотрудник не понял, что именно нужно делать. Какая функция в данном случае \"хромает\" у руководителя?', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Неверно!', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Именно так!', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Не совсем!', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Чтобы сотрудник понимал, что ему делать и чётко видел образ конечного результата, руководителю нужно грамотно ставить цели.', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Спасибо, что ответил на все вопросы! И у тебя {N} правильных ответов из 3', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Готов перейти к следующему блоку, в котором мы поговорим об уровнях профессионального развития сотрудников?', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Хорошо, возвращайся, я всегда на связи!', 'TEXT');")
cur.execute("INSERT INTO TALKS (MESSAGE, TYPE) VALUES ('Отлично, продолжаем!', 'TEXT');")
conn.commit()
conn.close()


